### ISSUE TITLE
[Table] DataGrid Not Displaying Rows After Prop Change

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [mui-org/material-ui-x#2002]
I am running into a situation where data is not being displayed in the free datagrid after pagination change.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When I change the rows prop in the data grid after pagination, the new rows are *not* displayed

## Expected Behavior 🤔
When I change the rows prop in the data grid after pagination, the new rows are displayed

## Steps to Reproduce 🕹

github create-react-app example: https://github.com/AndrewOttavianoAbb/DataGridTest
CodeSandbox example: https://codesandbox.io/s/relaxed-frost-5kfqt?file=/src/Demo.tsx

Steps:

1. Render a datagrid with enough rows of data to cause pagination in the free datagrid
2. Paginate to a subsequent page (one advancement is sufficient)
3. Click the "change rows" button
4. Observe that the data for the second 

## Context 🔦
I am using the data grid (free version) to display search results. We have a button for viewing all results and it returns back lots of rows so we are paginating the results in the table. If the user clicks this "view all" button, paginates, and searches, the search rows are not displayed in the table. I have confirmed that we are getting data back from our service and the data is being passed in properly via props. The prop change causes a re-render and on re-render, the data is not displayed in the table. See screenshots and this create-react-app [example](https://github.com/AndrewOttavianoAbb/DataGridTest).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212 (<- used to test)
    Edge: Spartan (44.18362.449.0)
```
</details>

**Comment by oliviertassinari** [comment]
@AndrewOttavianoAbb Thanks for the reproduction. I have simplified it a bit without `autoHeight` and fix the build bug: https://codesandbox.io/s/priceless-noyce-4ef3i?file=/src/Demo.tsx

**Comment by oliviertassinari** [comment]
Actually, the issue is more than 1 month old! It's already fixed in the latest version: https://codesandbox.io/s/wonderful-cerf-jx9qx?file=/src/Demo.tsx. I have searched on MUI, I can't see any other unsolved issues like this.

**Comment by eebbann** [comment]
my data grid not displaying 
`import * as React from 'react';
import { Container } from '@mui/material';
import { DataGrid, GridRowsProp, GridColDef } from '@mui/x-data-grid'


function UserList() {
    
      const columns = [
        { field: 'id', headerName: 'ID', width: 90 },
        {
          field: 'firstName',
          headerName: 'First name',
          width: 150,
          editable: true,
        },
        {
          field: 'lastName',
          headerName: 'Last name',
          width: 150,
          editable: true,
        },
        {
          field: 'age',
          headerName: 'Age',
          type: 'number',
          width: 110,
          editable: true,
        },
        {
          field: 'fullName',
          headerName: 'Full name',
          description: 'This column has a value getter and is not sortable.',
          sortable: false,
          width: 160,
          valueGetter: (params) =>
            `${params.row.firstName || ''} ${params.row.lastName || ''}`,
        },
      ];
      
      const rows = [
        { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
        { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
        { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
        { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
        { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
        { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
        { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
        { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
        { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
      ];

      return (
        <Containers x={{height: 350}}>
          <h1>Single items:</h1>
          <DataGrid
        rows={rows}
        columns={columns}
        pageSize={5}
        rowsPerPageOptions={[5]}
        checkboxSelection
        disableSelectionOnClick
      />
        </Containers>
      );
    }

export default UserList`

**Comment by SGR007** [comment]
> my data grid not displaying `import * as React from 'react'; import { Container } from '@mui/material'; import { DataGrid, GridRowsProp, GridColDef } from '@mui/x-data-grid'
> 
> function UserList() {
> 
> ```
>   const columns = [
>     { field: 'id', headerName: 'ID', width: 90 },
>     {
>       field: 'firstName',
>       headerName: 'First name',
>       width: 150,
>       editable: true,
>     },
>     {
>       field: 'lastName',
>       headerName: 'Last name',
>       width: 150,
>       editable: true,
>     },
>     {
>       field: 'age',
>       headerName: 'Age',
>       type: 'number',
>       width: 110,
>       editable: true,
>     },
>     {
>       field: 'fullName',
>       headerName: 'Full name',
>       description: 'This column has a value getter and is not sortable.',
>       sortable: false,
>       width: 160,
>       valueGetter: (params) =>
>         `${params.row.firstName || ''} ${params.row.lastName || ''}`,
>     },
>   ];
>   
>   const rows = [
>     { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
>     { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
>     { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
>     { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
>     { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
>     { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
>     { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
>     { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
>     { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
>   ];
> 
>   return (
>     <Containers x={{height: 350}}>
>       <h1>Single items:</h1>
>       <DataGrid
>     rows={rows}
>     columns={columns}
>     pageSize={5}
>     rowsPerPageOptions={[5]}
>     checkboxSelection
>     disableSelectionOnClick
>   />
>     </Containers>
>   );
> }
> ```
> 
> export default UserList`

add autoHeight prop

```jsx
<DataGrid
  ...
  autoHeight
/>
```

**Comment by eebbann** [comment]
Added that still not working 
Here’s my package.json aswell 
![Uploading image.jpg…]()

**Comment by BetterLuke** [comment]
> 

Hi, bro. I had a problem with the same scenario, the way I solved it was because I ignored the pagination mode stated by the documentation：https://mui.com/zh/components/data-grid/pagination/#server-side-pagination

As i explained，Because I am paging through the backend, after I change the paging mode and update the page on the paging group price, the data of the new rows is rendered normally

**Comment by matheussouza89** [comment]
After all this time the problem still persists... Disappointing.
autoHeight prop doesn't work
![image](https://user-images.githubusercontent.com/54581095/183139802-f372e9e9-685e-42e8-b9a4-71fc21db8aa0.png)

**Comment by brijsiyag** [comment]
set `paginationMode="server"`

**Comment by friemelb** [comment]
@brijsiyag that worked for me. When your using the server to control the pages aka page 1 === 10 and page 2 === 5, that is needed.

**Comment by marshallrelocation2** [comment]
@oliviertassinari https://lnkr.fun/dc2b436
