### ISSUE TITLE
[DataGrid] The filder panel changes the theme of the application

### ISSUE THREAD

**Issue by royalcala** [mui-org/material-ui-x#2807]
when i use filter in datagridpro the spacing of the other components change, and when I use the filter the color change of all the components

- [X ] The issue is present in the latest release.
- [ X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
the topbar is blue with the default values and change to white and black when I open a filter
![image](https://user-images.githubusercontent.com/12802822/136408526-c34ccb1e-8a36-4a26-97dd-763d19afb8a5.png)
the spacing change in the components
![image](https://user-images.githubusercontent.com/12802822/136408716-d17dc1b4-0f4a-4959-9b72-ff81ae3f2aa5.png)

changes the color of the top bar,  and the spacing
## Expected Behavior 🤔
![image](https://user-images.githubusercontent.com/12802822/136408441-2df71827-615f-4884-87b2-8c8961fe653f.png)
![image](https://user-images.githubusercontent.com/12802822/136408758-a6abb2f1-0495-4abb-a8f9-af4b8b6a129b.png)

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎
System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
  Binaries:
    Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.24.1 - ~/.nvm/versions/node/v15.4.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 92.0
  npmPackages:
    @emotion/react: latest => 11.4.1 
    @emotion/styled: latest => 11.3.0 
    @mui/core:  5.0.0-alpha.49 
    @mui/icons-material: ^5.0.1 => 5.0.1 
    @mui/lab: ^5.0.0-alpha.49 => 5.0.0-alpha.49 
    @mui/material: latest => 5.0.2 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/system:  5.0.2 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.1 
    @mui/x-data-grid: ^4.0.1 => 4.0.1 
    @mui/x-data-grid-pro: ^4.0.1 => 4.0.1 
    @mui/x-license-pro:  4.0.1 
    @types/react: 17.0.27 => 17.0.27 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.3 => 4.4.3

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
You are using MUI X v4 with MUI Core v5. Upgrading @mui/x-data-grid, @mui/x-data-grid-pro and @mui/x-license-pro to v5 should fix the problem.

**Comment by dnishiyama** [comment]
I am running into a similar issue where my UI is fine, but then after loading a page with a Data Grid on it, the UI breaks from an update to css rules for `.MuiBaseButton-root`. I have updated @mui/x-data-grid to 5.0.0-beta.4 and am still facing the problem.

**Comment by sidmirza4** [comment]
@dnishiyama I am facing the same issue. I am running @mui/x-data-grid-pro v5.0.0-beta.7.
Please fix the issue.

**Comment by flaviendelangle** [comment]
We would need someone to provide a reproduction case for us to fix it.
You can use this [template](https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc) as a starting point.

**Comment by sidmirza4** [comment]
Hi @flaviendelangle .
I tried to reproduce the error using the template that you have given, but as soon as I copied my code to Sandbox everything worked correctly. I am using styled-component engine instead of emotion. Can that be causing the issue?

**Comment by flaviendelangle** [comment]
I can't create a Codesandbox with the Styled Component aliases.
Could you do a Github repo with the same basic reproduction use case based on https://github.com/mui-org/material-ui/tree/master/examples/create-react-app-with-styled-components ? 

If it is caused by the switch to Styled Components the problem may be in the core.

**Comment by planetmall** [comment]
I am having the same issue where when DataGridPro loads the styling of my app is broken.
